### ISSUE TITLE
responsiveness mobile view

### ISSUE THREAD

**Issue by lyndseysc** [FACxBeamery/Week4_Tom_Thomas#25]
page looks great at all window sizes, great responsiveness! 

only prob is when you edit on mobile this looks a bit wild, i think the click triggers delete and edit at same time:

<img width="338" alt="Screenshot 2019-10-04 at 10 36 37" src="https://user-images.githubusercontent.com/35724145/66197804-10ec1880-e693-11e9-9e2c-dc7d3643d248.png">

**Comment by Oliversw** [comment]
![Screen Shot 2019-10-04 at 10 46 20 AM](https://user-images.githubusercontent.com/9094166/66198437-55c47f00-e694-11e9-9f78-c0dfaa7a020f.png)

On that note I would also suggest making the to do items take up much more of the screen at smaller widths. This is at the size of an iphoneSE which tends to be the smallest size that I will go to make sure that everything works.
