### ISSUE TITLE
Suggestion for todo item dom configuration

### ISSUE THREAD

**Issue by Joaoviana** [FACxBeamery/Week4_Tom_Thomas#27]
If you want the checkbox and the title to be on the left the options to the right, I would do it more or less in this way: 
> a div -> todo item
> inside the div:
> input checkbox
> p elem with the title
> button for editing
> button for removing

would set an a width for the p tag and would play around with the css. feel free to see how we did it in our project (see function `renderTodo()` )

**Comment by Oliversw** [comment]
This would also be a great time for using Flexbox. You could easily align all of the items to the right and then one (the to do title) to the left. That is if you want everything to line up!
